### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by manigopal** [mithilesh-parmar/Flutter-store#2]
@mithilesh-parmar 

- Most Selling Products at Homepage not loading

- When variation change the price for particular variation not loaded (Variable Products)

- Shows error 'Please choose variation' even variation chosen & even at simple products without variation

**Comment by mithilesh-parmar** [comment]
Hey @manigopal 
The app depends on Server which was freely hosted on a site, due to my inactivity They suspended my Server instance. This can cause various issues with the app. 

This project is just for reference for widgets and as to how one can consume the woocommerce api In flutter. 
This app is not supposed to be built upon as I built this when I was learning the framework. 

The project currently has outdated packages. I don’t get much time to contribute to this project but I’m thinking of recreating it with uncle bobs clean architecture. 
Thankyou

**Comment by manigopal** [comment]
@mithilesh-parmar 

waiting for your projects more with #wordpress #woocommerce 👍
